apiVersion: v1
kind: Service
metadata:
  name: {{ include "vm.fullname" . }}
  labels: {{- include "vm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "vm.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
