{{- if eq .Values.storage.backend "local" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaarta.fullname" . }}-storage
  labels: {{- include "vaarta.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.storage.local.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.local.size }}
{{- end }}
